### ISSUE TITLE
feedback rules does not work if there is multiple match

### ISSUE THREAD

**Issue by qiujian16** [open-cluster-management-io/work#196]
An example is in Gateway API, we want to get all the addresses form an array:

```
addresses:
- type: IPAddress
  value: 172.32.201.0
- type: IPAddress
  value: 172.32.202.0
```

Using json path in feedback rule does not work, since today's implementation only return the first matched item.
```
feedbackRules:
- type: JSONPaths
  jsonPaths:
  - name: addresses
    path: 'status.addresses[?(@.type=="IPAddress")].value'
```

Possible way we could solve is this we could let jsonPaths to return a marshaled json string if the returned type is not a know scalar type. But to avoid overusing the json string which could be very large, we also need to set a reasonable size limit.
